class cubo_semantico:

    # Formato del cubo semantico
    # var1        var2       =       +       *      /       &&      ||       >      <     >=     <=    !=    ==    =   

    # entero     entero     ENT     ENT     ENT   FLOAT   ERROR    ERROR    BOOL   BOOL  BOOL   BOOL  BOOL  BOOL  ENT
    # entero     flotante  FLOAT   FLOAT   FLOAT  FLOAT   ERROR    ERROR    BOOL   BOOL  BOOL   BOOL  BOOL  BOOL  ENT
    # entero     cadena    ERROR   ERROR   ERROR  ERROR   ERROR    ERROR    ERROR  ERROR ERROR  ERROR ERROR ERROR ERROR 
    # entero     caracter  ERROR   ERROR   ERROR  ERROR   ERROR    ERROR    ERROR  ERROR ERROR  ERROR ERROR ERROR ERROR  
    # entero     bool      ERROR   ERROR   ERROR  ERROR   ERROR    ERROR    ERROR  ERROR ERROR  ERROR ERROR ERROR ERROR  
     
    # flotante   entero    FLOAT   FLOAT   FLOAT  FLOAT   ERROR    ERROR    BOOL   BOOL  BOOL   BOOL  BOOL  BOOL  FLOAT
    # flotante   flotante  FLOAT   FLOAT   FLOAT  FLOAT   ERROR    ERROR    BOOL   BOOL  BOOL   BOOL  BOOL  BOOL  FLOAT
    # flotante   cadena    ERROR   ERROR   ERROR  ERROR   ERROR    ERROR    ERROR  ERROR ERROR  ERROR ERROR ERROR ERROR  
    # flotante   caracter  ERROR   ERROR   ERROR  ERROR   ERROR    ERROR    ERROR  ERROR ERROR  ERROR ERROR ERROR ERROR  
    # flotante   bool      ERROR   ERROR   ERROR  ERROR   ERROR    ERROR    ERROR  ERROR ERROR  ERROR ERROR ERROR ERROR  

    # cadena     entero    ERROR   ERROR   ERROR  ERROR   ERROR    ERROR    ERROR  ERROR ERROR  ERROR ERROR ERROR ERROR  
    # cadena     flotante  ERROR   ERROR   ERROR  ERROR   ERROR    ERROR    ERROR  ERROR ERROR  ERROR ERROR ERROR ERROR  
    # cadena     cadena    ERROR   ERROR   ERROR  ERROR   ERROR    ERROR    ERROR  ERROR ERROR  ERROR BOOL  BOOL  CADENA 
    # cadena     caracter  ERROR   ERROR   ERROR  ERROR   ERROR    ERROR    ERROR  ERROR ERROR  ERROR ERROR ERROR ERROR  
    # cadena     bool      ERROR   ERROR   ERROR  ERROR   ERROR    ERROR    ERROR  ERROR ERROR  ERROR ERROR ERROR ERROR  

    # caracter   entero    ERROR   ERROR   ERROR  ERROR   ERROR    ERROR    ERROR  ERROR ERROR  ERROR ERROR ERROR ERROR  
    # caracter   flotante  ERROR   ERROR   ERROR  ERROR   ERROR    ERROR    ERROR  ERROR ERROR  ERROR ERROR ERROR ERROR  
    # caracter   cadena    ERROR   ERROR   ERROR  ERROR   ERROR    ERROR    ERROR  ERROR ERROR  ERROR ERROR ERROR ERROR  
    # caracter   caracter  ERROR   ERROR   ERROR  ERROR   ERROR    ERROR    ERROR  ERROR ERROR  ERROR BOOL  BOOL  CHAR  
    # caracter   bool      ERROR   ERROR   ERROR  ERROR   ERROR    ERROR    ERROR  ERROR ERROR  ERROR ERROR ERROR ERROR  

    # bool       entero    ERROR   ERROR   ERROR  ERROR   ERROR    ERROR    ERROR  ERROR ERROR  ERROR ERROR ERROR ERROR 
    # bool       flotante  ERROR   ERROR   ERROR  ERROR   ERROR    ERROR    ERROR  ERROR ERROR  ERROR ERROR ERROR ERROR 
    # bool       cadena    ERROR   ERROR   ERROR  ERROR   ERROR    ERROR    ERROR  ERROR ERROR  ERROR ERROR ERROR ERROR 
    # bool       caracter  ERROR   ERROR   ERROR  ERROR   ERROR    ERROR    ERROR  ERROR ERROR  ERROR ERROR ERROR ERROR 
    # bool       bool      ERROR   ERROR   ERROR  ERROR   BOOL     BOOL     ERROR  ERROR ERROR  ERROR BOOL  BOOL  BOOL


    cubo_semantico = (
        ((ENT, ENT, ENT, FLOAT, ERROR, ERROR, BOOL, BOOL, BOOL, BOOL, BOOL, BOOL, ENT),
        (FLOAT, FLOAT, FLOAT, FLOAT, ERROR, ERROR, BOOL, BOOL, BOOL, BOOL, BOOL, BOOL, ENT),
        (ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR),
        (ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR),
        (ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR)
        ),
        ((FLOAT, FLOAT, FLOAT, FLOAT, ERROR, ERROR, BOOL, BOOL, BOOL, BOOL, BOOL, BOOL, FLOAT),
        (FLOAT, FLOAT, FLOAT, FLOAT, ERROR, ERROR, BOOL, BOOL, BOOL, BOOL, BOOL, BOOL, FLOAT),
        (ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR),
        (ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR),
        (ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR)
        ),
        ((ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR),
        (ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR),
        (ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, BOOL, BOOL, CADENA),
        (ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR),
        (ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR)
        ),
        ((ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR),
        (ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR),
        (ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR),
        (ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, BOOL, BOOL, CHAR),
        (ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR)
        )
        ((ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR),
        (ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR),
        (ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR),
        (ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR),
        (ERROR, ERROR, ERROR, ERROR, BOOL, BOOL, ERROR, ERROR, ERROR, ERROR, BOOL, BOOL, BOOL)
        )
        ) 